services:
  jupyter-quant:
    # image: gnzsnz/jupyter-quant:${IMAGE_VERSION}
    environment:
      APT_PROXY: ${APT_PROXY:-}
      BYODF: ${BYODF:-}
      SSH_KEYDIR: ${SSH_KEYDIR:-}
      TZ: ${QUANT_TZ:-}
      QUANDL_API_KEY: ${QUANDL_API_KEY}
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "admin" # Replace with a secure toke
    build:
      context: .
      dockerfile: Docker/Dockerfile.notebook
    restart: unless-stopped
    ports:
      - 8888:8888
    volumes:
      - quant_conf:/home/kuba/.config
      - quant_data:/home/kuba/.local
      - ${PWD}:/app

volumes:
  quant_conf:
  quant_data:
